### PR TITLE
Add typescript declaration file 

### PR DESCRIPTION
**Pull request by arminyahya**
I added declaration file so project with typescript can use benefit of typechecking of component.

### CODE REVIEW

**Comment by thebrodmann** [comment]
Looks like `develop` isn't the branch that you worked on.

**Comment by arminyahya** [comment]
@thebrodmann 
Looks like i have not permission to work on develop.

image

Git give me this when i want to push my changes from develop branch
Can u give me access?

**Comment by thebrodmann** [comment]
@arminyahya you worked on the `master` branch of your forked repo. Just make a PR from it to the `master` branch of this repo. There is no need for any permission.

**Comment by thebrodmann** [comment]
I opened another PR (#63) from the `master` branch of your forked repo. I think this one can be closed.

**Pull request closed without merging**
